import type { GameCard } from "./types";

export const ANIMALS_DECK_ES: GameCard[] = [
  {
    id: "elephant-image",
    pairKey: "elephant",
    type: "image",
    label: "Elephant",
    imageUrl: "/cards/animals/elephant.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "elephant-word",
    pairKey: "elephant",
    type: "word",
    label: "Elephant",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "giraffe-image",
    pairKey: "giraffe",
    type: "image",
    label: "Giraffe",
    imageUrl: "/cards/animals/giraffe.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "giraffe-word",
    pairKey: "giraffe",
    type: "word",
    label: "Giraffe",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "hippo-image",
    pairKey: "hippo",
    type: "image",
    label: "Hipo",
    imageUrl: "/cards/animals/hippo.png",
    difficulty: "medium",
    field: "animals",
  },
  {
    id: "hippo-word",
    pairKey: "hippo",
    type: "word",
    label: "Hipo",
    difficulty: "medium",
    field: "animals",
  },
  {
    id: "monkey-image",
    pairKey: "monkey",
    type: "image",
    label: "Monkey",
    imageUrl: "/cards/animals/monkey.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "monkey-word",
    pairKey: "monkey",
    type: "word",
    label: "Monkey",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "panda-image",
    pairKey: "panda",
    type: "image",
    label: "Panda",
    imageUrl: "/cards/animals/panda.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "panda-word",
    pairKey: "panda",
    type: "word",
    label: "panda",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "parrot-image",
    pairKey: "parrot",
    type: "image",
    label: "Parrot",
    imageUrl: "/cards/animals/parrot.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "parrot-word",
    pairKey: "parrot",
    type: "word",
    label: "Parrot",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "penguin-image",
    pairKey: "penguin",
    type: "image",
    label: "Penguin",
    imageUrl: "/cards/animals/penguin.png",
    difficulty: "medium",
    field: "animals",
  },
  {
    id: "penguin-word",
    pairKey: "penguin",
    type: "word",
    label: "Penguin",
    difficulty: "medium",
    field: "animals",
  },
  {
    id: "pig-image",
    pairKey: "pig",
    type: "image",
    label: "Pig",
    imageUrl: "/cards/animals/pig.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "pig-word",
    pairKey: "pig",
    type: "word",
    label: "Pig",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "rabbit-image",
    pairKey: "rabbit",
    type: "image",
    label: "Rabbit",
    imageUrl: "/cards/animals/rabbit.png",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "rabbit-word",
    pairKey: "rabbit",
    type: "word",
    label: "Rabbit",
    difficulty: "easy",
    field: "animals",
  },
  {
    id: "snake-image",
    pairKey: "snake",
    type: "image",
    label: "Snake",
    imageUrl: "/cards/animals/snake.png",
    difficulty: "medium",
    field: "animals",
  },
  {
    id: "snake-word",
    pairKey: "snake",
    type: "word",
    label: "Snake",
    difficulty: "medium",
    field: "animals",
  },
];
