import type { GameCard } from "./types";

export const COUNTRIES_DECK_ES: GameCard[] = [
  {
    id: "argentina-image",
    pairKey: "argentina",
    type: "image",
    label: "argentina",
    imageUrl: "/cards/countries/argentina.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "argentina-word",
    pairKey: "argentina",
    type: "word",
    label: "argentina",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "azerbaijan-image",
    pairKey: "azerbaijan",
    type: "image",
    label: "azerbaijan",
    imageUrl: "/cards/countries/azerbaijan.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "azerbaijan-word",
    pairKey: "azerbaijan",
    type: "word",
    label: "azerbaijan",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "brazil-image",
    pairKey: "brazil",
    type: "image",
    label: "brazil",
    imageUrl: "/cards/countries/brazil.png",
    difficulty: "medium",
    field: "countries",
  },
  {
    id: "brazil-word",
    pairKey: "brazil",
    type: "word",
    label: "brazil",
    difficulty: "medium",
    field: "countries",
  },
  {
    id: "canada-image",
    pairKey: "canada",
    type: "image",
    label: "canada",
    imageUrl: "/cards/countries/canada.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "canada-word",
    pairKey: "canada",
    type: "word",
    label: "canada",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "china-image",
    pairKey: "china",
    type: "image",
    label: "china",
    imageUrl: "/cards/countries/china.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "china-word",
    pairKey: "china",
    type: "word",
    label: "china",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "france-image",
    pairKey: "france",
    type: "image",
    label: "france",
    imageUrl: "/cards/countries/france.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "france-word",
    pairKey: "france",
    type: "word",
    label: "france",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "germany-image",
    pairKey: "germany",
    type: "image",
    label: "germany",
    imageUrl: "/cards/countries/germany.png",
    difficulty: "medium",
    field: "countries",
  },
  {
    id: "germany-word",
    pairKey: "germany",
    type: "word",
    label: "germany",
    difficulty: "medium",
    field: "countries",
  },
  {
    id: "japan-image",
    pairKey: "japan",
    type: "image",
    label: "japan",
    imageUrl: "/cards/countries/japan.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "japan-word",
    pairKey: "japan",
    type: "word",
    label: "japan",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "spain-image",
    pairKey: "spain",
    type: "image",
    label: "spain",
    imageUrl: "/cards/countries/spain.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "spain-word",
    pairKey: "spain",
    type: "word",
    label: "spain",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "turkey-image",
    pairKey: "turkey",
    type: "image",
    label: "turkey",
    imageUrl: "/cards/countries/turkey.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "turkey-word",
    pairKey: "turkey",
    type: "word",
    label: "turkey",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "chile-image",
    pairKey: "chile",
    type: "image",
    label: "chile",
    imageUrl: "/cards/countries/chile.png",
    difficulty: "easy",
    field: "countries",
  },
  {
    id: "chile-word",
    pairKey: "chile",
    type: "word",
    label: "chile",
    difficulty: "easy",
    field: "countries",
  },
];
